"""
summary_stats.py

Computes every number in the manuscript's "5.1.4 Summary statistics"
paragraph (AlarmOnto_V4.docx) directly from the live ontology / vocabulary /
knowledge-graph pipeline, so the reported figures cannot drift from what the
pipeline actually produces. Writes a ready-to-paste Markdown snippet to
DOCS/tables/summary_stats.md, mirroring corpus_stats.py's convention.

What each manuscript figure maps to
------------------------------------
  Unique alarm messages annotated       rows of DATA/ANNOTATION/consensus/
                                         p50_annotated.csv
  Triples before enrichment             the SAME ontology-driven builder
  Triples after enrichment              build_framework.py uses (build_alarmtype_
  Median triples/alarm before/after     triples), called on two versions of the
                                         annotated CSV: the real one ("after"),
                                         and a copy with every column blanked
                                         except alarmLabel/alarmPriority
                                         ("before" — exactly the fields present
                                         in the raw DATA/CORPUS/*.csv,
                                         pre-annotation). Reusing the real
                                         builder (never re-implementing it)
                                         means "before" is not a guess at what
                                         translation would produce — it is
                                         what the pipeline actually produces
                                         when handed only that information.
  MDA ontology classes / object         FRAMEWORK/ONTOLOGY/ontology.ttl, by owl:Class /
  properties / datatype properties      owl:ObjectProperty / owl:DatatypeProperty
  SKOS concepts / concept schemes       vocab_base.ttl UNION the concept stubs
                                         build_framework.py's own builder would
                                         generate for the current CSV (not the
                                         possibly-stale FRAMEWORK/VOCABULARY/
                                         vocab_generated.ttl on disk — regenerated
                                         in-process so this can't go stale either).
  Retrospective PoC events / triples    DATA/POC_EVENTS/events_data.csv row count;
                                         kg_inference.trig's default graph
                                         (the accumulated structural
                                         translation — see that file's own
                                         header for why named-graph ticks,
                                         which include OWL-reasoner
                                         entailments, are excluded).
  Resource utilization (classes /       owl:Class / owl:ObjectProperty / skos:Concept
  relations / concepts exercised)       usage counted over the OWL-RL closure (owlrl,
                                         same reasoner cq_QA.py/op_knowledge.py use) of
                                         onto+inference+the current KG — NOT a raw
                                         rdf:type scan, which undercounts badly (see
                                         resource_utilization_stats()'s docstring for
                                         why). Reported against the current annotation
                                         stage (pct_of_types), not as a design verdict.

Data-provenance caveat — read before citing the retrospective PoC numbers
---------------------------------------------------------------------------
DATA/POC_EVENTS/events_data.csv is currently SYNTHETIC placeholder data
generated by events_seed.py "for load and concurrency testing" (see that
script's own docstring) — it is explicitly NOT the authored real-world
alarm log. The numbers this script prints for the retrospective PoC section
are real outputs of the current pipeline, but they describe synthetic data,
not the real-world retrospective cohort the manuscript claims. Replace
events_data.csv with the authored dataset before citing those two numbers.

Usage
-----
  python3 summary_stats.py
"""

import re
import sys
from pathlib import Path
from statistics import median

import owlrl
import pandas as pd
from rdflib import Dataset, Graph
from rdflib.namespace import RDF, OWL, SKOS

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT       = SCRIPT_DIR.parent.parent   # CODE/reporting -> CODE -> Restructured
OUT_PATH   = ROOT / "DOCS" / "tables" / "summary_stats.md"

sys.path.append(str(SCRIPT_DIR.parent / "framework_build"))
import build_framework as R  # noqa: E402  (reuse the real builder, never reimplement it)

EVENTS_PATH = ROOT / "DATA" / "POC_EVENTS" / "events_data.csv"
TRIG_PATH   = ROOT / "EVALUATION" / "MDA-POC" / "kg_inference.trig"

# Which feasibility cutoff is annotated is read off build_framework.CSV_PATH's
# own filename (e.g. "p75_annotated.csv" -> 75) rather than hardcoded here, so
# this can't silently drift out of sync with the pipeline's actual cutoff the
# way the manuscript text and corpus_stats.py's cutoff once did independently.
CUTOFF_PCT          = int(re.match(r"p(\d+)_annotated", R.CSV_PATH.stem).group(1))
TOTAL_CORPUS_PATH   = ROOT / "DATA" / "CORPUS" / "Total_corpus.csv"
CUTOFF_CORPUS_PATH  = ROOT / "DATA" / "CORPUS" / f"Annotation_corpus_{CUTOFF_PCT}.csv"


def norm_key(label: str, priority: str) -> tuple:
    """Whitespace/case-normalized (label, priority) identity, matching
    corpus_stats.py's alarm-type key."""
    return (" ".join(str(label).split()).casefold(), " ".join(str(priority).split()).casefold())


# ── Shared pipeline context (ontology-derived, independent of which CSV
#    cells are filled — built once, reused for both the "before" and
#    "after" builder runs) ────────────────────────────────────────────────

def build_context(onto: Graph, base: Graph, inference: Graph, df: pd.DataFrame) -> dict:
    """Replays build_framework.main()'s setup (steps 2-6) far enough to hand
    build_alarmtype_triples() everything it needs, without writing files."""
    tree = R.derive_class_tree(onto, R.ROOT_CLASS)

    columns = [c for c in df.columns if c in R.COLUMN_SCHEMES]
    bindings = R.derive_bindings(onto, columns)
    stateful = set(onto.subjects(R.MDA.nodeKind, R.MDA.Stateful))
    node_columns, node_kind, leaf_specs = {}, {}, []
    for col in columns:
        kind, prop, cls, scheme = bindings[col]
        if kind == "node":
            node_columns[cls] = col
            marker = next((o for o in onto.objects(cls, R.MDA.nodeKind) if o in R.KIND_OF), None)
            node_kind[cls] = R.KIND_OF.get(marker, "referential")
        else:
            if any(str(o).lower() == "true" for o in onto.objects(prop, R.MDA.refinesUniversalIdentity)):
                role = "identity"
            elif cls in stateful:
                role = "state"
            else:
                role = "plain"
            leaf_specs.append((cls, prop, col, role, scheme))

    target_types = {}
    for prop, extra in onto.subject_objects(R.MDA.targetType):
        target_types.setdefault(prop, []).append(extra)

    index = R.build_notation_index(base)
    missing = R.collect_missing(df, columns, bindings, index)
    vocab_out = R.build_vocab_graph(missing, bindings, base)

    labels = {str(v).strip() for v in df[R.LABEL_COLUMN].dropna() if str(v).strip()}
    for t in R.build_label_vocab(labels, base):
        vocab_out.add(t)

    already_known = {s for s in vocab_out.subjects(RDF.type, SKOS.Concept)}
    inferred_concepts = R.collect_inference_concepts(inference, base, onto, already_known)
    for t in R.build_inference_concept_stubs(inferred_concepts, base, onto):
        vocab_out.add(t)

    index = R.build_notation_index(base, vocab_out)  # rebuilt to include the stubs just generated
    metric_recipe = R.build_metric_recipe(inference)
    administers_map = R.build_administers_map(inference)

    return dict(tree=tree, node_kind=node_kind, node_columns=node_columns,
                leaf_specs=leaf_specs, target_types=target_types,
                index=index, metric_recipe=metric_recipe, vocab_out=vocab_out,
                administers_map=administers_map)


def per_row_triple_counts(df: pd.DataFrame, ctx: dict) -> list:
    """One mda:AlarmType's worth of per-alarm-particular triples per row,
    via the real builder run against a fresh graph pair per row — the
    exact same function call build_framework.py makes, just not accumulated
    into one shared graph, so each row's own contribution is visible."""
    counts, failed = [], []
    for i, row in df.iterrows():
        kg, ref = Graph(), Graph()
        try:
            R.build_alarmtype_triples(row, kg, ref, ctx["index"], ctx["tree"],
                                       ctx["node_kind"], ctx["node_columns"],
                                       ctx["leaf_specs"], ctx["target_types"],
                                       ctx["metric_recipe"], ctx["administers_map"])
        except KeyError as e:
            failed.append(f"  row {i + 2}: {e}")
            continue
        counts.append(len(kg))
    if failed:
        print("[WARN] Row(s) skipped while counting triples:")
        print("\n".join(failed))
    return counts


def _local_name(iri) -> str:
    return str(iri).rsplit("#", 1)[-1].rsplit("/", 1)[-1]


def resource_utilization_stats(onto: Graph, inference: Graph, vocab_full: Graph,
                                kg_combined: Graph, ref_combined: Graph,
                                df_after: pd.DataFrame, ctx: dict) -> dict:
    """
    Resource utilization against the CURRENTLY annotated corpus (n_alarms of
    n_total_types — see alarm_representation_stats()'s pct_of_types) — this
    is a snapshot of how much of the framework this annotation stage
    exercises, not a verdict on the framework's design: it rises as
    annotation proceeds toward the eventual cutoff, and should always be
    reported alongside that annotation-coverage figure, never alone.

    A naive rdf:type / triple-object scan on the asserted KG badly
    undercounts, for two independent reasons (both confirmed by hand against
    a real annotated row before writing this):
      1. An individuated node is typed by its concrete SKOS concept (e.g.
         mda:SpO2), not by the OWL class itself (mda:Metric) — the concept
         is only rdfs:subClassOf that class, so a bare rdf:type scan misses
         every class that is ever refined into a concrete concept.
      2. The entire clinical perspective (PhysiologicalProperty/Process/
         Organ/OrganSystem) is derived by OWL-RL reasoning over
         inference.ttl's axioms (see 5.1.3's "reasoning over these axioms")
         and never appears in the asserted translation graph at all — a
         bare scan makes the framework's central reasoning payoff look like
         dead weight.
    Both are fixed by materializing the real OWL-RL closure (the same
    owlrl.DeductiveClosure(OWLRL_Semantics) call cq_QA.py and
    op_knowledge.py already use for CQ/PoC evaluation) before counting
    anything, instead of inspecting the raw asserted graph.
    """
    reasoned = Graph()
    for g in (onto, inference, kg_combined, ref_combined, vocab_full):
        for t in g:
            reasoned.add(t)
    owlrl.DeductiveClosure(owlrl.OWLRL_Semantics).expand(reasoned)

    all_classes = set(onto.subjects(RDF.type, OWL.Class))
    all_object_props = set(onto.subjects(RDF.type, OWL.ObjectProperty))

    # skos:topConceptOf marks each scheme's own generic header concept (e.g.
    # "Device") — never itself assigned to an alarm (5.1.2's "shallow
    # hierarchy from the scheme's general category to more specific terms").
    # Counting it as an annotatable, potentially-orphaned concept would be
    # like counting a folder icon as an unused file.
    top_concepts = set(vocab_full.subjects(SKOS.topConceptOf, None))
    all_concepts = set(vocab_full.subjects(RDF.type, SKOS.Concept))
    annotatable_concepts = all_concepts - top_concepts

    # Scoped to triples rooted at an actual annotated-alarm individual
    # (kg_combined/ref_combined's own subjects, pre-reasoning) — NOT a scan
    # of the whole reasoned graph. That distinction matters: OWL-RL's own
    # closure adds reflexive/symmetric noise for every resource (e.g. every
    # concept X gets `X owl:sameAs X`), and the static graph carries
    # concept-to-concept schema/recipe facts (e.g. inference.ttl's metric
    # recipe `ArterialPressureAnalysis producesMetric ABP`) — both would
    # make a concept or property look "used" via pure self-reference or
    # schema plumbing even when no alarm ever carries it. Confirmed by hand:
    # a naive whole-graph scan showed 100% concept utilization, which
    # evaporated once scoped to alarm-rooted triples only.
    kg_subjects = set(kg_combined.subjects()) | set(ref_combined.subjects())
    alarm_rooted = [(s, p, o) for s, p, o in reasoned if s in kg_subjects]

    used_types   = {o for s, p, o in alarm_rooted if p == RDF.type}
    used_props   = {p for s, p, o in alarm_rooted}
    used_objects = {o for s, p, o in alarm_rooted}

    used_classes = all_classes & used_types
    used_object_props = all_object_props & used_props
    used_concepts = annotatable_concepts & (used_types | used_objects)

    # Classes exercised on literally EVERY annotated row regardless of that
    # row's own content — structural scaffolding (e.g. mda:Patient, forced
    # active with no CSV column of its own at all — see build_framework.py's
    # `active.add(MDA.Patient)`) rather than a sign of real per-alarm data.
    # Computed on the raw (unreasoned) per-row graphs: a forced/trivial node
    # is always typed directly by its bare class (the "no concept resolved"
    # fallback), so this needs no reasoning pass to detect.
    per_row_type_sets = []
    for _, row in df_after.iterrows():
        kg_row, ref_row = Graph(), Graph()
        try:
            R.build_alarmtype_triples(row, kg_row, ref_row, ctx["index"], ctx["tree"],
                                       ctx["node_kind"], ctx["node_columns"],
                                       ctx["leaf_specs"], ctx["target_types"],
                                       ctx["metric_recipe"], ctx["administers_map"])
        except KeyError:
            continue
        per_row_type_sets.append(set(kg_row.objects(None, RDF.type)) & all_classes)
    always_present = set.intersection(*per_row_type_sets) if per_row_type_sets else set()

    return dict(
        n_classes_used=len(used_classes), n_classes_total=len(all_classes),
        pct_classes_used=len(used_classes) / len(all_classes) * 100,
        n_relations_used=len(used_object_props), n_relations_total=len(all_object_props),
        pct_relations_used=len(used_object_props) / len(all_object_props) * 100,
        n_concepts_used=len(used_concepts), n_concepts_total=len(annotatable_concepts),
        pct_concepts_used=len(used_concepts) / len(annotatable_concepts) * 100,
        always_present_classes=sorted(_local_name(c) for c in always_present),
    )


# ── Ontology / vocabulary / corpus-annotation statistics ───────────────────

def alarm_representation_stats() -> dict:
    onto = Graph(); onto.parse(R.ONTOLOGY_PATH, format="turtle")
    base = Graph(); base.parse(R.VOCAB_BASE_PATH, format="turtle")
    inference = Graph(); inference.parse(R.INFERENCE_PATH, format="turtle")

    df_after = pd.read_csv(R.CSV_PATH, sep=";", dtype=str)
    df_after.columns = df_after.columns.str.strip()
    n_alarms = len(df_after)

    # Corpus-coverage figures for "X unique alarm messages (X%) were selected
    # to represent Y% of the total alarm volume": Y is NOT assumed to equal
    # CUTOFF_PCT verbatim, since build_corpus_cutoffs.py applies that cutoff
    # per department stratum, so the combined share can land a few points
    # above the nominal cutoff — computed here from the actual corpus files
    # instead of repeating the manuscript's old hardcoded "99%" mistake.
    total_corpus  = pd.read_csv(TOTAL_CORPUS_PATH, sep=";", encoding="utf-8-sig")
    cutoff_corpus = pd.read_csv(CUTOFF_CORPUS_PATH, sep=";", encoding="utf-8-sig")
    n_total_types = len({norm_key(l, p) for l, p in
                          zip(total_corpus["Alarm_label"], total_corpus["Alarm_priority"])})
    pct_of_types  = n_alarms / n_total_types * 100
    pct_of_volume = cutoff_corpus["Quant_count"].sum() / total_corpus["Quant_count"].sum() * 100

    ctx = build_context(onto, base, inference, df_after)

    df_before = df_after.copy()
    keep = {R.LABEL_COLUMN, R.PRIORITY_COLUMN}
    for col in df_before.columns:
        if col not in keep:
            df_before[col] = pd.NA

    before_counts = per_row_triple_counts(df_before, ctx)
    after_counts  = per_row_triple_counts(df_after, ctx)

    triples_before, triples_after = sum(before_counts), sum(after_counts)

    # A combined ("after") run also produces `ref_out` — deduplicated universal
    # triples, e.g. precoordinate()'s shorthand concepts like
    # device:PhysiologicalMonitor_Philips — which build_framework.main() merges
    # into vocab_out AFTER the KG build step. Reproduced here for the same
    # reason: those concepts are part of "the accompanying SKOS vocabulary"
    # but only ever materialize once the full KG has been built.
    kg_combined, ref_combined = R.build_graphs(
        df_after, ctx["index"], ctx["tree"], ctx["node_kind"], ctx["node_columns"],
        ctx["leaf_specs"], ctx["target_types"], ctx["metric_recipe"], ctx["administers_map"])
    assert len(kg_combined) == triples_after, (
        f"combined KG build ({len(kg_combined)} triples) disagrees with the "
        f"per-row sum ({triples_after}) — the two code paths should be identical.")
    for t in ref_combined:
        ctx["vocab_out"].add(t)

    # Cross-check against the on-disk kg_generated.ttl — a mismatch means
    # that file is stale relative to the current CSV/ontology and should be
    # regenerated with `python3 build_framework.py` before citing these numbers.
    kg_on_disk = Graph()
    on_disk_note = ""
    if R.KG_OUT_PATH.exists():
        kg_on_disk.parse(R.KG_OUT_PATH, format="turtle")
        if len(kg_on_disk) != triples_after:
            on_disk_note = (f"[WARN] FRAMEWORK/KNOWLEDGE_BASE/kg_generated.ttl on disk has {len(kg_on_disk)} triples, "
                             f"recomputed 'after' total is {triples_after} — the file on disk is stale; "
                             f"run `python3 build_framework.py` to refresh it.")

    n_classes         = len(set(onto.subjects(RDF.type, OWL.Class)))
    n_object_props    = len(set(onto.subjects(RDF.type, OWL.ObjectProperty)))
    n_datatype_props  = len(set(onto.subjects(RDF.type, OWL.DatatypeProperty)))

    vocab_full = Graph()
    for t in base:
        vocab_full.add(t)
    for t in ctx["vocab_out"]:
        vocab_full.add(t)
    n_concepts = len(set(vocab_full.subjects(RDF.type, SKOS.Concept)))
    n_schemes  = len(set(vocab_full.subjects(RDF.type, SKOS.ConceptScheme)))

    util = resource_utilization_stats(onto, inference, vocab_full, kg_combined, ref_combined,
                                       df_after, ctx)

    return dict(
        n_alarms=n_alarms,
        n_total_types=n_total_types, pct_of_types=pct_of_types, pct_of_volume=pct_of_volume,
        triples_before=triples_before, triples_after=triples_after,
        pct_increase=(triples_after - triples_before) / triples_before * 100,
        median_before=median(before_counts), median_after=median(after_counts),
        n_classes=n_classes, n_object_props=n_object_props, n_datatype_props=n_datatype_props,
        n_concepts=n_concepts, n_schemes=n_schemes,
        on_disk_note=on_disk_note,
        **util,
    )


# ── Retrospective proof-of-concept statistics ───────────────────────────────

def retrospective_stats() -> dict:
    events = pd.read_csv(EVENTS_PATH, sep=";", dtype=str)
    n_events = len(events)

    ds = Dataset()
    ds.parse(TRIG_PATH, format="trig")
    default_graph = ds.default_graph if hasattr(ds, "default_graph") else ds.default_context
    n_triples_default = len(default_graph)

    named = [g for g in (ds.graphs() if hasattr(ds, "graphs") else ds.contexts())
             if g.identifier != default_graph.identifier]
    n_triples_deduped_all = len({t for g in named for t in g} | set(default_graph))

    return dict(n_events=n_events,
                n_triples=n_triples_default,
                n_triples_all_ticks_deduped=n_triples_deduped_all,
                n_ticks=len(named))


# ── Reporting ────────────────────────────────────────────────────────────────

def render_markdown(rep: dict, retro: dict) -> str:
    lines = [
        "## 5.1.4 Summary statistics — computed values",
        "",
        f"A total of **{rep['n_alarms']}** unique alarm messages (**{rep['pct_of_types']:.1f}%** "
        f"of the **{rep['n_total_types']}** unique alarm types in the corpus) were selected to "
        f"represent **{rep['pct_of_volume']:.1f}%** of the total alarm volume and consequently "
        "annotated by domain experts. Translation of the information "
        f"directly available in the original CSV files resulted in **{rep['triples_before']}** "
        "RDF triples. After incorporating the technical and clinical knowledge identified "
        "during expert annotation, the resulting alarm representations contained "
        f"**{rep['triples_after']}** triples, corresponding to an increase of "
        f"**{rep['pct_increase']:.1f}%** in represented knowledge. The median number of "
        f"triples per alarm increased from **{rep['median_before']:.0f}** before enrichment to "
        f"**{rep['median_after']:.0f}** after enrichment.",
        "",
        f"The MDA ontology contains **{rep['n_classes']}** classes, **{rep['n_object_props']}** "
        f"object properties, and **{rep['n_datatype_props']}** datatype properties. The "
        f"accompanying SKOS vocabulary contains **{rep['n_concepts']}** concepts across "
        f"**{rep['n_schemes']}** concept schemes, including terminology identified and added "
        "during the alarm annotation process.",
        "",
        f"Resource utilization — at the current annotation stage covering **{rep['pct_of_types']:.1f}%** "
        f"of unique alarm types — exercised **{rep['pct_classes_used']:.1f}%** of ontology classes "
        f"(**{rep['n_classes_used']}**/**{rep['n_classes_total']}**), **{rep['pct_relations_used']:.1f}%** "
        f"of object properties (**{rep['n_relations_used']}**/**{rep['n_relations_total']}**), and "
        f"**{rep['pct_concepts_used']:.1f}%** of annotatable vocabulary concepts "
        f"(**{rep['n_concepts_used']}**/**{rep['n_concepts_total']}**), after materializing the "
        "framework's OWL-RL entailments (scheme-header concepts excluded from the concept count — "
        "see caveat below).",
        "",
        "> **Caveats:** (1) These figures measure utilization *of the current annotation stage*, "
        "not a ceiling on the framework's design — they are expected to rise as annotation proceeds "
        f"toward the full corpus. (2) {', '.join(f'`{c}`' for c in rep['always_present_classes'])} "
        "are asserted on every annotated alarm regardless of that alarm's specific content, "
        "reflecting structural scaffolding rather than data-dependent enrichment — counted as "
        "'used' above, but not evidence of rich per-alarm content.",
        "",
        f"For the retrospective proof-of-concept, **{retro['n_events']}** real-world alarm "
        "events were translated into structured representation, resulting in a knowledge "
        f"graph containing **{retro['n_triples']}** triples.",
        "",
        "> **Caveat:** `DATA/POC_EVENTS/events_data.csv` is currently synthetic placeholder data "
        "(see `events_seed.py`'s docstring), not the authored real-world retrospective cohort. "
        "The two retrospective-PoC numbers above must be recomputed once that file is replaced "
        "with the real dataset — everything else in this table is already computed from the "
        "real pipeline outputs.",
        "",
        f"*(Retrospective KG size policy: {retro['n_triples']} counts only "
        f"`kg_inference.trig`'s default graph — the structural translation of the event stream. "
        f"Including every per-tick situational snapshot plus OWL-reasoner entailments, deduplicated "
        f"across all {retro['n_ticks']} ticks, gives {retro['n_triples_all_ticks_deduped']} triples "
        "instead; pick whichever matches what the sentence is meant to describe.)*",
    ]
    if rep["on_disk_note"]:
        lines += ["", rep["on_disk_note"]]
    return "\n".join(lines)


def main() -> None:
    rep = alarm_representation_stats()
    retro = retrospective_stats()

    print(f"[corpus]     {rep['n_alarms']} unique annotated alarm messages "
          f"({rep['pct_of_types']:.1f}% of {rep['n_total_types']} unique alarm types), "
          f"representing {rep['pct_of_volume']:.1f}% of total alarm volume")
    print(f"[triples]    before enrichment: {rep['triples_before']} "
          f"(median {rep['median_before']:.0f}/alarm)")
    print(f"[triples]    after enrichment:  {rep['triples_after']} "
          f"(median {rep['median_after']:.0f}/alarm)")
    print(f"[triples]    increase: {rep['pct_increase']:.1f}%")
    print(f"[ontology]   {rep['n_classes']} classes, {rep['n_object_props']} object properties, "
          f"{rep['n_datatype_props']} datatype properties")
    print(f"[vocab]      {rep['n_concepts']} concepts across {rep['n_schemes']} concept schemes")
    print(f"[util]       classes: {rep['pct_classes_used']:.1f}% ({rep['n_classes_used']}/{rep['n_classes_total']}), "
          f"relations: {rep['pct_relations_used']:.1f}% ({rep['n_relations_used']}/{rep['n_relations_total']}), "
          f"concepts: {rep['pct_concepts_used']:.1f}% ({rep['n_concepts_used']}/{rep['n_concepts_total']})")
    print(f"[util]       always-present classes (structural, not data-dependent): "
          f"{', '.join(rep['always_present_classes'])}")
    print(f"[retro]      {retro['n_events']} events, {retro['n_triples']} triples "
          f"(default graph); {retro['n_triples_all_ticks_deduped']} triples if all "
          f"{retro['n_ticks']} ticks' snapshots are included")
    if rep["on_disk_note"]:
        print(rep["on_disk_note"])

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render_markdown(rep, retro), encoding="utf-8")
    print(f"\n[out]        Wrote {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
